trigger: none

pool: 
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Get AzDO User ID'
  inputs:
    azureSubscription: 'rm-prod-extensions-service-connection'
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az rest -u https://app.vssps.visualstudio.com/_apis/profile/profiles/me --resource 6e219f2c-0bef-429f-9108-40f360499831