blank_issues_enabled: false
contact_links:
  - name: Developer Community
    url: https://developercommunity.visualstudio.com/AzureDevOps
    about: For other Azure DevOps issues
  - name: Agent issue
    url: https://github.com/microsoft/azure-pipelines-agent/issues/new
    about: If you have issues with pipelines agent, please place your issues here.
  - name: Task issue
    url: https://github.com/microsoft/azure-pipelines-tasks/issues/new
    about: If you have issues with ADO task, please place your issues here.
  - name: Security issue
    url: https://github.com/microsoft/azure-pipelines-tasks/security/policy
    about: For security issues, please check our policy
 